version: "3.8"
services:
  database:
    image: "postgres:14-alpine"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=reporting_app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reporting_app_development
    volumes:
      - postgres_data_development2:/var/lib/postgresql/data
  
  redis:
    image: "redis:7"
    ports:
      - 6380:6380

volumes:
  postgres_data_development2: {}
